import json
import logging
import os
from datetime import UTC, datetime
from typing import Any

logger = logging.getLogger(__name__)


class ReportGenerator:
    """Generates markdown and JSON operational reports from snapshot data.

    Advisory output only. Reports are human-readable summaries.
    """

    def __init__(self, output_dir: str = "data/reports") -> None:
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

    def snapshot_report(self, snapshot: dict[str, Any], snapshot_id: int) -> str:
        data = snapshot.get("data", snapshot)
        target = data.get("target", "unknown")
        scanned_at = data.get("scanned_at", "unknown")
        repo = data.get("scanner_results", {}).get("results", {}).get("repo_scanner", {})
        llm_detections = data.get("llm_detections", [])

        lines = [
            "# Operational Snapshot Report",
            f"**Generated:** {_now()}",
            f"**Snapshot ID:** {snapshot_id}",
            f"**Target:** `{target}`",
            f"**Scanned At:** {scanned_at}",
            "",
        ]

        if repo:
            git_info = (
                f"Yes — branch: `{repo.get('git_branch') or 'unknown'}`"
                if repo.get("has_git")
                else "No"
            )
            lines += [
                "## Repository Intelligence",
                f"- **Name:** {repo.get('name', 'unknown')}",
                f"- **Primary Language:** {repo.get('primary_language', 'unknown')} "
                f"({repo.get('total_files', 0)} total files)",
                f"- **Git:** {git_info}",
                f"- **Package Managers:** {', '.join(repo.get('package_managers', [])) or 'none detected'}",
                f"- **Frameworks:** {', '.join(repo.get('frameworks', [])) or 'none detected'}",
                f"- **Docker:** {'Yes' if repo.get('docker', {}).get('present') else 'No'}",
                f"- **CI/CD:** {', '.join(repo.get('ci_cd', [])) or 'none detected'}",
                f"- **AI Config Files:** {', '.join(repo.get('ai_config_files', [])) or 'none'}",
                f"- **LLM SDKs (packages):** {', '.join(repo.get('llm_sdks', [])) or 'none detected'}",
                "",
            ]

        if llm_detections:
            lines += [
                "## LLM Usage Detected in Source Code",
                "| Provider | Confidence | Purpose | Evidence |",
                "|----------|-----------|---------|---------|",
            ]
            for det in llm_detections:
                evidence = det["evidence"][0] if det.get("evidence") else "—"
                lines.append(
                    f"| {det['provider']} | {det['confidence']} | "
                    f"{det['purpose_category']} | {evidence} |"
                )
            lines.append("")
        else:
            lines += [
                "## LLM Usage",
                "_No LLM SDK usage detected in source files._",
                "",
            ]

        caps = repo.get("capabilities", {}) if repo else {}
        if caps:
            lines += ["## Capabilities"]
            for cap, val in caps.items():
                lines.append(f"- **{cap.replace('_', ' ').title()}:** {'Yes' if val else 'No'}")
            lines.append("")

        lines += [
            "---",
            "*Advisory only — all operational decisions require human review.*",
            "*Generated by AI Operational Memory — Observe automatically. Decide manually.*",
        ]

        report = "\n".join(lines)
        self._save(f"snapshot_{snapshot_id}.md", report)
        return report

    def drift_report(self, drift: dict[str, Any], prev_id: int, curr_id: int) -> str:
        human_readable = drift.get("human_readable", [])

        lines = [
            "# Operational Drift Report",
            f"**Generated:** {_now()}",
            f"**Comparing:** Snapshot #{prev_id} → Snapshot #{curr_id}",
            f"**Changes Detected:** {drift.get('change_count', 0)}",
            "",
        ]

        if not human_readable:
            lines += ["## Result", "_No operational drift detected._", ""]
        else:
            lines += ["## Changes Detected", ""]
            for item in human_readable:
                lines.append(f"- {item}")
            lines.append("")

        lines += [
            "---",
            "*Advisory only — all operational decisions require human review.*",
            "*Generated by AI Operational Memory*",
        ]

        report = "\n".join(lines)
        self._save(f"drift_{prev_id}_to_{curr_id}.md", report)
        return report

    def export_json(self, data: dict[str, Any], filename: str) -> str:
        path = os.path.join(self.output_dir, filename)
        content = json.dumps(data, indent=2, default=str)
        with open(path, "w") as f:
            f.write(content)
        logger.info("JSON report exported", extra={"path": path})
        return content

    def _save(self, filename: str, content: str) -> None:
        path = os.path.join(self.output_dir, filename)
        with open(path, "w") as f:
            f.write(content)
        logger.debug("Report saved", extra={"path": path})


def _now() -> str:
    return datetime.now(UTC).strftime("%Y-%m-%d %H:%M:%S UTC")
